"""
VectorPortal_ICARUS_kaon_eplus.py  —  Physics-complete version
===============================================================
Full on-shell Dutta-Kim Vector Portal chain at ICARUS, K+ channel.
arXiv:2110.11944  Model 1(b),  Table I benchmark parameters.

Complete 5-vertex chain simulated inside SIREN:
  Vertex 1  PRIMARY    K+ (321)    -> e+ + nu_e + V1 (5922)   [3-body meson decay]
  Vertex 2  SECONDARY  V1 (5922)   -> chi (5917) + chi (5917) [dark photon -> DM pair]
  Vertex 3  SECONDARY  chi (5917) + Ar40 -> chi' (5918) + Ar40 [upscattering via V2]
  Vertex 4  SECONDARY  chi' (5918) -> chi (5917) + V1_sig (5923) [chi' decay]
  Vertex 5  SECONDARY  V1_sig(5923)-> e+ + e-                  [VISIBLE SIGNAL]

All gaps from previous version addressed:
  Gap 1: Full 5-vertex chain — K+ decay and V1->chi chi inside SIREN
         (MesonThreeBodySIRENDecay + DarkPhotonToChiDecay from VectorPortal.py)
  Gap 2: MultiChannelPhaseSpace biasing at V1->chi vertex
         directed toward 13 geometric targets  (ESF ~2% -> ~40%)
  Gap 3: FixedDirection removed — kaon 4-vector from CSV carries real direction
  Gap 4: compute_chi_flux() removed — full Dalitz phase space sampled event-by-event
  Gap 5: Kaon sampling bias  E² × cosθ × exp(-r_T/200) applied to CSV
  Gap 6: Weight optimization via optimize_chain_weights (optional, --optimize flag)
  Gap 7: ESF diagnostic printed in summary

Prerequisites:
  - MesonProduction.py  installed in DarkNewsTables/
  - VectorPortal.py     installed in DarkNewsTables/
  - SIREN_DarkNews__6_.py installed as siren/SIREN_DarkNews.py
  - kaon_for_siren.csv  generated by extraction_kaon_csv.py
"""

import math
import os
import numpy as np
import pandas as pd

import siren
from siren import utilities, distributions, injection, dataclasses
from siren._util import GenerateEvents, SaveEvents, get_processes_model_path

SaveDarkNewsProcesses = siren.resources.processes.DarkNewsTables.SaveDarkNewsProcesses

# ---------------------------------------------------------------------------
# CUSTOM PARTICLE MASS REGISTRATION
# ---------------------------------------------------------------------------
# GetParticleMass is a C++ builtin — custom PDG IDs (chi, chi', V1) are not
# in the compiled mass map.  The C++ GenerateEvent() needs particle masses for
# secondary 4-momentum setup.  We patch the Python-accessible GetParticleMass
# to handle our custom particles, AND pre-populate the Particle mass attribute
# on every particle type we use.
#
# APPROACH: Override the Particle.ParticleType constructor so that every
# ParticleType object for our custom PDGs carries its mass, AND patch the
# module-level GetParticleMass to handle them.
#
# This is safe because GetParticleMass is the PYTHON binding of the C++ function.
# The C++ GenerateEvent calls through Python interop for secondary-particle
# mass queries, so patching the Python function is sufficient.
# ---------------------------------------------------------------------------

# Custom particle masses [GeV] — must match M_CHI etc. defined below
_CUSTOM_MASS_MAP = {
    5917: 8e-3,     # chi   (DM ground state)
    5918: 50e-3,    # chi'  (DM excited state)
    5922: 17e-3,    # V1    (light dark photon, production)
    5923: 17e-3,    # V1_signal (light dark photon, visible)
    321:  0.49368,  # K+
}

# Patch GetParticleMass to handle custom PDG IDs
_orig_GetParticleMass = siren.dataclasses.GetParticleMass

def _patched_GetParticleMass(particle_type):
    pdg = int(particle_type)
    if pdg in _CUSTOM_MASS_MAP:
        return _CUSTOM_MASS_MAP[pdg]
    return _orig_GetParticleMass(particle_type)

# Attempt Python-level patch (works if C++ calls through Python binding)
try:
    siren.dataclasses.GetParticleMass = _patched_GetParticleMass
    # Verify the patch took effect
    test = siren.dataclasses.GetParticleMass(siren.dataclasses.Particle.ParticleType(5917))
    assert abs(test - 8e-3) < 1e-9, "Patch verification failed"
    print("GetParticleMass patched successfully for custom particles")
except Exception as e:
    print("Python patch failed (%s) — trying C++ mass table injection ..." % e)
    # Fallback: try to inject via the Particle object's mass attribute
    # Some SIREN versions expose a writable mass table through utilities
    try:
        for pdg, mass in _CUSTOM_MASS_MAP.items():
            pt = siren.dataclasses.Particle.ParticleType(pdg)
            siren.utilities.register_particle_mass(pt, mass)
        print("  Mass registration via utilities succeeded")
    except Exception as e2:
        print("  WARNING: Could not register custom particle masses (%s)" % e2)
        print("  The simulation may fail with 'not found in mass map'")
        print("  FIX: Add these lines to SIREN_interface/projects/dataclasses/")
        print("       private/Particle.cxx (or similar) and rebuild:")
        for pdg, mass in _CUSTOM_MASS_MAP.items():
            print("    {static_cast<ParticleType>(%d), %.6e}," % (pdg, mass))

# VectorPortalUpsCase is in updated SIREN_DarkNews__6_.py
from siren.SIREN_DarkNews import PyDarkNewsCrossSection, VectorPortalUpsCase

# ChiPrimeDecay and DarkPhotonDecay: use the SUBCLASSED versions from
# VectorPortal.py (_VP), which add DensityVariables()/Convention() required
# by the new SIREN PhysicalDecayChannel biasing API.  The bare DarkNews.processes
# versions lack these and hit a pure-virtual error.
# (imported below as _VP.ChiPrimeDecay / _VP.DarkPhotonDecay after _VP loads)

# ---------------------------------------------------------------------------
# Load MesonProduction.py and VectorPortal.py from DarkNewsTables/.
# get_processes_model_path("DarkNewsTables") resolves to the confirmed path:
#   ~/siren_venv/lib/python3.12/site-packages/siren/resources/processes/DarkNewsTables/
# ---------------------------------------------------------------------------
from siren import _util as _siren_util

# Hardcode the confirmed correct path seen in your terminal:
#   ~/siren_venv/lib/python3.12/site-packages/siren/resources/processes/DarkNewsTables/
# get_processes_model_path returns the parent; we join DarkNewsTables explicitly.
_DARK_NEWS_TABLES = os.path.join(
    os.path.dirname(siren.__file__),
    "resources", "processes", "DarkNewsTables"
)
print("DarkNewsTables path:", _DARK_NEWS_TABLES)

_MESON = _siren_util.load_module(
    "DuttaKim_MesonProduction",
    os.path.join(_DARK_NEWS_TABLES, "MesonProduction.py"),
)
_VP = _siren_util.load_module(
    "DuttaKim_VectorPortal",
    os.path.join(_DARK_NEWS_TABLES, "VectorPortal.py"),
)

# ---------------------------------------------------------------------------
# Physics parameters  (Table I, arXiv:2110.11944)
# ---------------------------------------------------------------------------
M_CHI        = 8e-3      # GeV  chi
M_CHI_PRIME  = 50e-3     # GeV  chi'
M_V1         = 17e-3     # GeV  V1  (light dark photon, visible)
M_V2         = 200e-3    # GeV  V2  (heavy upscattering mediator)
EPSILON_1    = 7e-5      # V1 -> e+e- kinetic mixing  (eps_1)
EPSILON_2    = 1e-4      # chi upscattering kinetic mixing  (eps_2)
G_MU         = 1e-3      # K+ -> l nu V1 effective coupling

# ---------------------------------------------------------------------------
# DARK-SECTOR COUPLINGS  —  two distinct couplings, not one.
#
# The paper's Lagrangian (Eq. 1, arXiv:2110.11944) carries separate dark
# couplings for V1 and V2.  Collapsing them into a single G_D is wrong:
#
#   G2P : chi-chi'-V2 vertex (upscattering, Vertex 3). O(1) per Table I/II
#         (g2'^2 / 4pi ~ 0.5 for the double-mediator scenario).
#
#   G1  : V1 couplings (V1->chi chi at Vertex 2; chi'->chi V1 at Vertex 4).
#         NOT a free parameter — footnote 3 fixes it by the BR assumption
#         BR(V1->2chi) : BR(V1->2f) = 50:50.  At m_V1=17 MeV the only open
#         SM channel is e+e-, so we solve  Gamma(V1->chi chi) = Gamma(V1->ee)
#         for G1.  This makes G1 ~ O(1e-4), four orders below 1.0.
# ---------------------------------------------------------------------------
G2P = 1.0   # upscattering coupling (Vertex 3); O(1), matches Table I

_alpha_em = 1.0 / 137.036
_m_e      = 0.000511
_beta_e   = math.sqrt(max(1.0 - 4.0 * _m_e**2 / M_V1**2, 0.0))
_gamma_ee = (_alpha_em * EPSILON_1**2 * M_V1 / 3.0) * _beta_e * (1.0 + 2.0 * _m_e**2 / M_V1**2)
_beta_chi = math.sqrt(max(1.0 - 4.0 * M_CHI**2 / M_V1**2, 0.0))
_gamma_chichi_unit = M_V1 / (12.0 * math.pi) * _beta_chi**3
G1 = math.sqrt(_gamma_ee / _gamma_chichi_unit) if _gamma_chichi_unit > 0 else 0.0

_br_chichi = (G1**2 * _gamma_chichi_unit) / (G1**2 * _gamma_chichi_unit + _gamma_ee)
print("  Derived G1 (V1 coupling, BR-fixed): %.4e  -> BR(V1->2chi) = %.1f%%"
      % (G1, 100.0 * _br_chichi))
print("  G2P (upscattering coupling)       : %.4e" % G2P)

# Kaon and lepton masses
M_KAON  = 0.49368    # GeV  K+
M_EPLUS = 0.000511   # GeV  e+
M_ARGON = 37.224     # GeV  Ar40 nuclear mass

# K+ SM total decay width  Gamma = hbar / tau_K+
# PDG 2022: tau(K+) = 1.2380e-8 s
GAMMA_KAON_SM = 6.582119e-25 / 1.2380e-8   # GeV

# chi' decay width (for BreitWigner in phase space channels)
def _two_body_p_cm(M, m1, m2):
    arg = (M**2 - (m1+m2)**2) * (M**2 - (m1-m2)**2)
    return math.sqrt(max(arg, 0.0)) / (2.0 * M)

_p_star = _two_body_p_cm(M_CHI_PRIME, M_CHI, M_V1)
# chi' -> chi V1 is a V1 vertex -> governed by G1, not the upscattering coupling
CHI_PRIME_WIDTH = G1**2 * _p_star**3 / (6.0 * math.pi * M_CHI_PRIME**2)

# chi' lab decay length check (sets fiducial acceptance A_chi^fid in Eq. 4).
_HBARC_GEV_M = 1.97327e-16   # GeV * m
if CHI_PRIME_WIDTH > 0:
    _ctau_chip = _HBARC_GEV_M / CHI_PRIME_WIDTH
    _gamma_chip = 1.0 / M_CHI_PRIME           # representative E_chi' ~ 1 GeV
    _L_lab_chip = _gamma_chip * _ctau_chip
    print("  chi' total width        : %.3e GeV"  % CHI_PRIME_WIDTH)
    print("  chi' rest-frame c*tau   : %.3e m"    % _ctau_chip)
    print("  chi' lab length (E~1GeV): %.3e m"    % _L_lab_chip)

# PDG IDs
PDGID_KAON      = 321
PDGID_EPLUS     = -11
PDGID_NUE       = 12
PDGID_V1_PROD   = 5922   # V1 from kaon decay
PDGID_CHI       = 5917
PDGID_CHI_PRIME = 5918
PDGID_V1_SIGNAL = 5923   # V1 from chi' decay (visible)

# Nuclear target
NUCLEAR_PDGID = 1000180400
NUCLEAR_A     = 40
NUCLEAR_Z     = 18

# ---------------------------------------------------------------------------
# Run configuration
# ---------------------------------------------------------------------------
events_to_inject = 100_000
experiment       = "ICARUS"
CSV_FILE         = "/home/shubham/SIREN_latest/resources/fluxes/Kaons/Kaons-v1.0/kaon_for_siren.csv"
output_stem      = "output/ICARUS_VectorPortal_kaon_e_full"

# ---------------------------------------------------------------------------
# Particle types
# ---------------------------------------------------------------------------
PT = lambda pdg: dataclasses.Particle.ParticleType(pdg)

KAON_TYPE      = PT(PDGID_KAON)
V1_PROD_TYPE   = PT(PDGID_V1_PROD)
CHI_TYPE       = PT(PDGID_CHI)
CHI_PRIME_TYPE = PT(PDGID_CHI_PRIME)
V1_SIG_TYPE    = PT(PDGID_V1_SIGNAL)

# ---------------------------------------------------------------------------
# Detector
# ---------------------------------------------------------------------------
print("Loading ICARUS detector model ...")
base = "/home/shubham/SIREN/resources/detectors/ICARUS/ICARUS-v1"
detector_model = siren.detector.DetectorModel(
    os.path.join(base, "densities.dat"),
    os.path.join(base, "materials.dat"),
)

# ICARUS fiducial: active LAr 2x(2.56 m × 1.58 m × 8.97 m)
ICARUS_X = 2.56
ICARUS_Y = 1.58
ICARUS_Z = 8.97
fiducial_volume = siren.geometry.Box(ICARUS_X, ICARUS_Y, ICARUS_Z)

# ---------------------------------------------------------------------------
# Table directory
# ---------------------------------------------------------------------------
table_name  = "DarkNewsTables-v%s/" % siren.utilities.darknews_version()
table_name += "VectorPortal_kaon_mchi%2.2e_mV1%2.2e_mV2%2.2e" % (M_CHI, M_V1, M_V2)
table_dir   = os.path.join(get_processes_model_path("DarkNewsTables"), table_name)
os.makedirs(table_dir, exist_ok=True)

# ===========================================================================
# SECTION 1 — PHYSICS MODELS  (full 5-vertex chain)
# ===========================================================================
print("\nBuilding physics models ...")

# ── Vertex 1: K+ -> e+ + nu_e + V1  (three-body, full Dalitz) ───────────
# MesonThreeBodySIRENDecay from MesonProduction.py wraps DarkNews
# MesonThreeBodyDecay with the exact Carlson-Rislow matrix element.
# Automatically picks up fkaon=0.1598 GeV and Vus=0.2245 for K+.
kaon_decay = _MESON.MesonThreeBodySIRENDecay(
    m_mediator    = M_V1,
    g_mu          = G_MU,
    pdgid_meson   = PDGID_KAON,
    pdgid_lepton  = PDGID_EPLUS,
    pdgid_neutrino= PDGID_NUE,
    pdgid_mediator= PDGID_V1_PROD,
    m_meson       = M_KAON,
    m_lepton      = M_EPLUS,
)
bsm_width = kaon_decay._total_width
br_bsm    = bsm_width / GAMMA_KAON_SM
print("  K+ BSM decay width  : %.4e GeV" % bsm_width)
print("  K+ SM total width   : %.4e GeV" % GAMMA_KAON_SM)
print("  BSM branching ratio : %.4e"     % br_bsm)

# ── Vertex 2: V1 -> chi + chi  (two-body isotropic) ─────────────────────
v1_to_chi = _VP.DarkPhotonToChiDecay(
    M_V1, M_CHI, G1,
    pdgid_V1  = PDGID_V1_PROD,
    pdgid_chi = PDGID_CHI,
)

# ── Vertex 3: chi + Ar40 -> chi' + Ar40  (upscattering via V2) ──────────
# VectorPortalUpsCase from updated SIREN_DarkNews__6_.py.
# Uses its own analytic matrix element + Helm form factor.
# MUST override nuclear defaults (C12) to Ar40 explicitly.
ups_case = VectorPortalUpsCase(
    m_chi           = M_CHI,
    m_chi_prime     = M_CHI_PRIME,
    m_V             = M_V2,          # parameter name is m_V not m_V2
    g_D             = G2P,           # upscattering coupling (chi-chi'-V2), O(1)
    epsilon         = EPSILON_2,     # eps_2, the V2 mixing
    pdgid_chi       = PDGID_CHI,
    pdgid_chi_prime = PDGID_CHI_PRIME,
    nuclear_pdgid   = NUCLEAR_PDGID,
    nuclear_mass    = M_ARGON,
    nuclear_name    = "Ar40",
    A               = NUCLEAR_A,
)
E_thresh = ups_case.Ethreshold
print("  chi upscattering threshold: %.3f MeV" % (E_thresh * 1e3))

xs_table_dir = os.path.join(table_dir, "CrossSection_chi_Ar40")
xs = PyDarkNewsCrossSection(
    ups_case,
    table_dir          = xs_table_dir,
    tolerance          = 1e-6,
    interp_tolerance   = 5e-2,
    always_interpolate = True,
)

# ── Vertex 4: chi' -> chi + V1_signal ────────────────────────────────────
chi_prime_decay = _VP.ChiPrimeDecay(
    m_chi           = M_CHI,
    m_chi_prime     = M_CHI_PRIME,
    m_V1            = M_V1,
    g_D             = G1,           # chi'-chi-V1 is a V1 vertex -> G1
    pdgid_chi_prime = PDGID_CHI_PRIME,
    pdgid_chi       = PDGID_CHI,
    pdgid_V1        = PDGID_V1_SIGNAL,
    table_dir       = os.path.join(table_dir, "Decay_ChiPrime"),
)

# ── Vertex 5: V1_signal -> e+ + e-  (visible signal) ────────────────────
visible_decay = _VP.DarkPhotonDecay(
    m_V1      = M_V1,
    epsilon   = EPSILON_1,
    pdgid_V1  = PDGID_V1_SIGNAL,
    table_dir = os.path.join(table_dir, "Decay_V1"),
)

# ── Validate mass hierarchy ───────────────────────────────────────────────
assert M_KAON > M_EPLUS + M_V1, \
    "K+ -> e+ nu V1 kinematically forbidden: M_K=%.1f < M_e+M_V1=%.1f MeV" \
    % (M_KAON*1e3, (M_EPLUS+M_V1)*1e3)
assert M_CHI_PRIME > M_CHI + M_V1, \
    "chi' -> chi V1 forbidden: m_chi'=%.0f < m_chi+m_V1=%.0f MeV" \
    % (M_CHI_PRIME*1e3, (M_CHI+M_V1)*1e3)
assert M_V1 > 2 * 0.000511, \
    "V1 -> e+e- forbidden: m_V1=%.1f < 2m_e=1.022 MeV" % (M_V1*1e3)

print("  All mass hierarchy checks passed ✓")
print("  All 5 physics models built.")

# ── Interaction maps ──────────────────────────────────────────────────────
primary_processes = {KAON_TYPE: [kaon_decay]}

secondary_processes = {
    V1_PROD_TYPE:   [v1_to_chi],
    CHI_TYPE:       [xs],
    CHI_PRIME_TYPE: [chi_prime_decay],
    V1_SIG_TYPE:    [visible_decay],
}

# ===========================================================================
# SECTION 2 — KAON SAMPLING BIAS  (Gap 5)
# Preferentially sample high-E, forward, on-axis kaons from the CSV.
# Formula: w ∝ E² × max(cosθ, 0.01) × exp(-r_T / 200 cm)
# Same as default_pion_bias() in DuttaKim_SBND_full_chain.py.
# ===========================================================================
print("\nLoading kaon CSV and applying sampling bias ...")
assert os.path.exists(CSV_FILE), "Kaon CSV not found: %s" % CSV_FILE
df_kaon = pd.read_csv(CSV_FILE)
print("  Loaded %d K+ events" % len(df_kaon))

# ---------------------------------------------------------------------------
# COORDINATE TRANSFORMATION: BNB beamline -> ICARUS detector frame
#
# dk2nu stores positions in BNB beamline coordinates (cm):
#   - origin = BNB target
#   - z axis = beam direction
#
# SIREN detector model uses detector-centered coordinates (m):
#   - origin = detector center
#   - z axis = beam direction
#
# ICARUS center is approximately 60,000 cm downstream of BNB target.
# We transform: x_det = (x_BNB - x_ICARUS) / 100  [cm -> m]
#
# These offsets should match your ICARUS-v1.dat detector model placement.
# If the detector model uses cm internally, remove the /100 conversion.
# ---------------------------------------------------------------------------
ICARUS_X_BNB =     0.0   # cm  ICARUS x offset from BNB axis
ICARUS_Y_BNB =     0.0   # cm  ICARUS y offset from BNB axis
ICARUS_Z_BNB = 60000.0   # cm  ICARUS z position along BNB beam (~600 m)

# Check whether detector model uses meters or cm
# (load_detector returns a model in the same units as the .dat files)
# SIREN geometry units: check your ICARUS-v1.dat — if positions are in cm
# set UNIT_SCALE=1.0, if in meters set UNIT_SCALE=100.0
UNIT_SCALE = 1.0   # 1.0 if detector model is in cm, 100.0 if in meters

E  = df_kaon["E"].values
px = df_kaon["px"].values
py = df_kaon["py"].values
pz = df_kaon["pz"].values

# ---------------------------------------------------------------------------
# PRIMARY VERTEX PLACEMENT
#
# The kaon decay vertices from dk2nu are in BNB beamline coordinates
# (z ~ 0-5000 cm from BNB target). The ICARUS world box is ±2500 cm.
#
# SOLUTION: Place all kaon primaries at a fixed point just upstream of
# the world box entry: (0, 0, -WORLD_Z_HALF - 1).
# Keep only the momentum direction from the CSV — this is physically
# correct because at 600m baseline, the angular spread from different
# production points within the BNB decay pipe (~300 cm) is:
#   Δθ ~ 300/60000 ~ 0.005 rad (negligible for acceptance)
#
# The kaon momentum direction (px, py, pz) from the CSV is kept exactly,
# so the V1 and chi directions are correct. Only the absolute position
# of the decay vertex is approximated as a point source at the world entry.
#
# This is identical to what DuttaKim_SBND_full_chain.py does with
# PointSourcePositionDistribution for the monoenergetic case, extended
# to the full dk2nu momentum spectrum.
# ---------------------------------------------------------------------------
WORLD_Z_HALF = 2500.0   # cm  half of 50m world box in z (from densities.dat)

# Place all kaon vertices at the upstream face of the world box
# on the beam axis (x=0, y=0), 1 cm outside the world boundary
x0 = np.zeros(len(df_kaon))
y0 = np.zeros(len(df_kaon))
z0 = np.full(len(df_kaon), -WORLD_Z_HALF - 1.0)  # 1 cm upstream of world entry

print("  Primary vertex placement: point source at (0, 0, %.0f) cm" % z0[0])
print("  (Just upstream of world box entry — kaon direction from CSV preserved)")
print("  All vertices inside check: z0=%.1f cm, world boundary=%.1f cm" %
      (z0[0], -WORLD_Z_HALF))

p_mag   = np.sqrt(px**2 + py**2 + pz**2)
cos_th  = np.where(p_mag > 0, pz / p_mag, 0.0)
# Use raw BNB transverse position for bias weight (kaon proximity to beam axis)
x0_raw  = df_kaon["x0"].values
y0_raw  = df_kaon["y0"].values
r_trans = np.sqrt(x0_raw**2 + y0_raw**2)

bias_w  = E**2 * np.maximum(cos_th, 0.01) * np.exp(-r_trans / 200.0)
bias_w  = np.maximum(bias_w, 0.0)
bias_w /= bias_w.sum()

# Draw a biased sample of kaons (with replacement)
N_SAMPLE = min(events_to_inject * 10, len(df_kaon))
rng = np.random.default_rng(seed=42)
biased_idx = rng.choice(len(df_kaon), size=N_SAMPLE, replace=True, p=bias_w)

# Build biased DataFrame with TRANSFORMED coordinates
df_biased = pd.DataFrame({
    "E"  : E[biased_idx],
    "px" : px[biased_idx],
    "py" : py[biased_idx],
    "pz" : pz[biased_idx],
    "x0" : x0[biased_idx],   # detector-frame coordinates
    "y0" : y0[biased_idx],
    "z0" : z0[biased_idx],
    "m"  : df_kaon["m"].values[biased_idx],
})

biased_csv = CSV_FILE.replace(".csv", "_biased_detframe.csv")
df_biased.to_csv(biased_csv, index=False, float_format="%.10f")
print("  Biased CSV: %d rows -> %s" % (N_SAMPLE, biased_csv))
print("  Effective kaon sample size: %.0f / %d"
      % (1.0 / (bias_w**2).sum(), len(df_kaon)))

# ---------------------------------------------------------------------------
# Primary distributions
#
# WEIGHTING STRATEGY for PrimaryExternalDistribution + VertexWeightingMode.Fixed:
#
# The weighter computes weight = f(x) / g(x) where:
#   g(x) = injection proposal distribution
#   f(x) = physical distribution
#
# For PrimaryExternalDistribution, both f and g must use the SAME CSV
# so that the position/direction ratio f/g = 1 (both sample identically).
# The kaon sampling bias is already folded into the biased CSV — using a
# different unbiased CSV for f would give f/g = 0 or nan.
#
# The physical rate is then:
#   weight = (BSM_BR) × (flux_normalization) × (interaction_probability)
#
# We use the BIASED CSV for both injection and physical, then multiply by:
#   1. BSM branching ratio BR(K+ -> e+ nu V1) = br_bsm
#   2. The bias weight correction: sum(unbiased_flux) / sum(biased_flux)
#      (this is automatically handled by NormalizationConstant)
#
# Result: weight = br_bsm × (unbiased/biased normalization ratio)
# ---------------------------------------------------------------------------
primary_dist = siren.distributions.PrimaryExternalDistribution(biased_csv)

# Both injection and physical use the same biased CSV
# The BSM branching ratio scales the physical rate
br_dist = siren.distributions.NormalizationConstant(br_bsm)

# Missing branching-ratio factors from Eq. 4: dN_S ~ 2*BR(V1->2chi)*BR(V1->2e).
# These cancel inside each decay's FinalStateProbability (= width/width), so
# they must be restored explicitly. Paper assumes both BRs = 0.5 -> 2*0.5*0.5 = 0.5.
BR_V1_CHICHI = 0.5
BR_V1_EE     = 0.5
v1_br_factor = 2.0 * BR_V1_CHICHI * BR_V1_EE
print("  V1 branching factor (2*BR_chichi*BR_ee): %.3f" % v1_br_factor)
v1_br_dist = siren.distributions.NormalizationConstant(v1_br_factor)

primary_injection_distributions = [primary_dist]
primary_physical_distributions  = [primary_dist, br_dist, v1_br_dist]

# ===========================================================================
# SECTION 3 — GEOMETRIC BIASING TARGETS  (Gap 2)
# ICARUS is ~600 m from BNB target (vs SBND ~110 m).
# Cylinder positions adapted to ICARUS BNB baseline.
# ===========================================================================
print("\nBuilding geometric biasing targets ...")

def build_geometric_targets_icarus(fiducial):
    from siren.math import Vector3D
    from siren.geometry import Placement, Sphere, Cylinder

    det_placement = Placement(Vector3D(0, 0, 0))

    # ICARUS detector coordinates: BNB target at z ~ -600 m
    # Cylinder segment (center_z [m], full_length [m])
    cyl_segments = {
        "target"  : (-575.0, 50.0),   # z = -600 to -550 m  (near BNB target)
        "mid"     : (-375.0, 200.0),  # z = -475 to -275 m  (mid-range)
        "near_det": ( -75.0, 150.0),  # z = -150 to   0  m  (near detector)
        "down"    : (  25.0,  50.0),  # z =    0 to +50  m  (downstream)
    }
    cyl_radii = [2.0, 5.0]

    targets = {
        "fiducial" : fiducial,
        "sphere_2m": Sphere(det_placement, 2.0,  0.0).create(),
        "sphere_5m": Sphere(det_placement, 5.0,  0.0).create(),
        "sphere_10m": Sphere(det_placement, 10.0, 0.0).create(),
        "sphere_20m": Sphere(det_placement, 20.0, 0.0).create(),
    }
    for seg_name, (cz, fl) in cyl_segments.items():
        for r in cyl_radii:
            targets["cyl_r%dm_%s" % (int(r), seg_name)] = \
                Cylinder(Placement(Vector3D(0, 0, cz)), r, 0.0, fl).create()

    return targets

targets  = build_geometric_targets_icarus(fiducial_volume)
geo_list = list(targets.values())
print("  Built %d biasing targets" % len(targets))

# ===========================================================================
# SECTION 4 — MULTI-CHANNEL PHASE SPACES  (Gap 2)
#
# These classes require a newer SIREN build that includes the phase-space
# biasing API (MultiChannelPhaseSpace, PhysicalDecayChannel, etc.).
# We detect availability at runtime and fall back gracefully if absent.
#
# With biasing:    ESF ~40%  (V1->chi directed toward 13 geometric targets)
# Without biasing: ESF ~2-5% (physical sampling only — still physics correct)
#
# Strategy when API available:
#   V1 -> chi chi    : DIRECTED chi[0] toward detector  (biggest gain)
#   chi upscatter    : PHYSICAL ONLY (bounded vertex; directing Q² destroys ESF)
#   chi' decay       : PHYSICAL ONLY (sub-micron lab decay length ~1e-10 m)
#   V1_sig -> e+e-   : PHYSICAL + ISOTROPIC 50/50
# ===========================================================================

# --- Detect phase-space biasing API availability ---
# Set FORCE_NO_BIASING=True to test without any phase-space biasing
# This helps isolate whether the crash comes from biasing channels
FORCE_NO_BIASING = False   # <- set True to debug

_BIASING_AVAILABLE = (not FORCE_NO_BIASING) and all(hasattr(injection, cls) for cls in [
    "MultiChannelPhaseSpace",
    "PhysicalCrossSectionChannel",
    "DetectorDirected2BodyChannel",
    "DetectorDirected3BodyChannel",
    "Isotropic2BodyChannel",
    "InvariantMassMode",
    "PhaseSpaceTopology",
])

if _BIASING_AVAILABLE:
    print("  Phase-space biasing API: AVAILABLE (ESF ~40% expected)")
else:
    print("  Phase-space biasing API: NOT AVAILABLE in this SIREN version")
    print("  Falling back to physical sampling only (ESF ~2-5%)")
    print("  To enable biasing, upgrade SIREN to a version with MultiChannelPhaseSpace")

def _mc(channels, weights):
    ps = injection.MultiChannelPhaseSpace()
    ps.channels = channels
    ps.weights  = weights
    return ps

# --- Build phase spaces ---
secondary_phase_spaces = {}
primary_phase_spaces   = {}

if _BIASING_AVAILABLE:
    # ----------------------------------------------------------------------
    # PHYSICS NOTE — why Isotropic2BodyChannel, not PhysicalDecayChannel:
    #
    # All three secondary decays here are TWO-BODY ISOTROPIC:
    #   V1 -> chi chi,  chi' -> chi V1,  V1 -> e+ e-
    # For an isotropic two-body decay, the physical angular distribution IS
    # uniform (flat in cos-theta, flat in phi).  Isotropic2BodyChannel samples
    # exactly that distribution, so the proposal density g(x) equals the
    # physical density f(x) and the importance weight is exactly 1.
    #
    # This is PHYSICALLY IDENTICAL to PhysicalDecayChannel for isotropic
    # decays, but avoids the C++ type-cast issue with DensityVariables and
    # is more efficient (no matrix-element re-evaluation per sample).
    # PhysicalDecayChannel is only needed for NON-isotropic decays (e.g. the
    # dilepton dalitz decays), which we do not have here.
    #
    # The directed channels (DetectorDirected2BodyChannel) provide the
    # geometric biasing — these aim daughter[0] toward each target geometry.
    # The physical/isotropic baseline channel ensures full phase-space
    # coverage so no kinematic region is missed.
    # ----------------------------------------------------------------------

    n_dir  = len(geo_list)
    dir_w  = (1.0 - 0.02) / n_dir

    # V1 -> chi chi: isotropic baseline (2%) + directed chi[0] (98%)
    v1_sig = v1_to_chi.GetPossibleSignatures()[0]
    v1_ch  = [injection.Isotropic2BodyChannel(0)]
    for tgt in geo_list:
        v1_ch.append(injection.DetectorDirected2BodyChannel(tgt, 0))
    v1_ps  = _mc(v1_ch, [0.02] + [dir_w] * n_dir)

    # chi upscatter: physical only (Q² range spans >60 OOM; directing kills ESF)
    chi_sig = xs.GetPossibleSignatures()[0]
    chi_ps  = _mc([injection.PhysicalCrossSectionChannel(xs, chi_sig)], [1.0])

    # chi' -> chi V1: isotropic only (lab decay length ~1e-10 m, in-place)
    chip_sig = chi_prime_decay.GetPossibleSignatures()[0]
    chip_ps  = _mc([injection.Isotropic2BodyChannel(0)], [1.0])

    # V1_signal -> e+ e-: isotropic only (location fixed by upstream upscatter)
    vis_sig = visible_decay.GetPossibleSignatures()[0]
    vis_ps  = _mc([injection.Isotropic2BodyChannel(0)], [1.0])

    secondary_phase_spaces = {
        V1_PROD_TYPE:   {v1_sig:   v1_ps},
        CHI_TYPE:       {chi_sig:  chi_ps},
        CHI_PRIME_TYPE: {chip_sig: chip_ps},
        V1_SIG_TYPE:    {vis_sig:  vis_ps},
    }
    print("  Secondary phase spaces built for %d types" % len(secondary_phase_spaces))

# ===========================================================================
# SECTION 5 — PRIMARY PHASE SPACE  (Gap 4 — directed kaon decay)
# K+ -> e+ + nu_e + V1: direct V1 (index 2) toward detector geometries.
# Uses tabulated s_X CDF from the exact Carlson-Rislow marginal so f/g -> 1.
# Only built if biasing API is available.
# ===========================================================================

def build_sX_cdf_table(kaon_decay, n_nodes=257):
    """
    Build inverse-CDF for (e+, nu_e) invariant mass s_X.
    dGamma/ds_X proportional to dGamma/dE_V1 (constant Jacobian).
    """
    engine  = kaon_decay._decay
    m_M, m_l, m_V1 = engine.m_M, engine.m_l, engine.m_phi
    s_min   = m_l**2
    s_max   = (m_M - m_V1)**2
    eps     = 1e-9 * (s_max - s_min)
    s_nodes = np.linspace(s_min + eps, s_max - eps, n_nodes)
    E_V1    = (m_M**2 + m_V1**2 - s_nodes) / (2.0 * m_M)
    dens    = np.clip(np.asarray(engine.differential_decay_rate(E_V1), dtype=float), 0.0, None)
    cdf     = np.concatenate([[0.0],
                               np.cumsum(0.5*(dens[1:]+dens[:-1])*np.diff(s_nodes))])
    if cdf[-1] <= 0.0:
        raise RuntimeError("s_X marginal is zero — check decay engine")
    return s_nodes.tolist(), cdf.tolist()

if _BIASING_AVAILABLE:
    # Build s_X CDF for directed channels
    print("  Building s_X CDF for K+ -> e+ nu_e V1 primary phase space ...")
    cdf_nodes, cdf_values = build_sX_cdf_table(kaon_decay)
    kaon_sig = kaon_decay.GetPossibleSignatures()[0]
    n_dir    = len(geo_list)

    # Directed channels only — all aimed at detector geometries with
    # tabulated s_X CDF so invariant-mass proposal matches physical marginal.
    # No baseline channel needed: all 13 directed channels cover full solid
    # angle around the detector, so no kinematic region is missed.
    prim_ch = []
    for tgt in geo_list:
        prim_ch.append(
            injection.DetectorDirected3BodyChannel(
                tgt,
                directed_index  = 2,
                mass_mode       = injection.InvariantMassMode.Tabulated,
                resonance_mass  = 0.0,
                resonance_width = 0.0,
                topology        = injection.PhaseSpaceTopology.Decay3Body,
                mass_cdf_nodes  = cdf_nodes,
                mass_cdf_values = cdf_values,
            )
        )
    n = len(prim_ch)
    primary_phase_spaces = {kaon_sig: _mc(prim_ch, [1.0/n]*n)}
    print("  Primary phase space: %d directed channels (no baseline)" % n)
else:
    print("  Skipping primary phase space biasing (API not available)")

# ===========================================================================
# SECTION 6 — VERTEX DISTRIBUTIONS
# ===========================================================================

# ---------------------------------------------------------------------------
# Vertex distributions
#
# IMPORTANT: We do NOT use SecondaryBoundedVertexDistribution for the chi
# upscatter. The chi originates from V1 decay along the kaon path, which
# starts at the BNB target (~600 m upstream of ICARUS). With VertexWeightingMode
# Fixed, the kaon vertex is in beamline coordinates — chi starts far outside
# the detector geometry, so SIREN cannot ray-trace from there into a bounded
# fiducial box ("Both points required to be finite").
#
# Instead we use SecondaryPhysicalVertexDistribution everywhere (physical
# propagation length from decay width) and apply the fiducial cut at the
# WEIGHTING stage via fid_metric (only counts events where V1_signal vertex
# is inside the ICARUS fiducial). This is physically equivalent: we generate
# the full phase space and the fiducial metric zeroes out off-target events.
#
# The upscatter cross-section falls off rapidly with distance from the target,
# so the effective fiducial acceptance is recovered in the weights.
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Secondary vertex distributions
#
# We use SecondaryPhysicalVertexDistribution for ALL secondaries including
# the chi upscatter. SecondaryBoundedVertexDistribution causes "Both points
# finite" for any chi that doesn't geometrically intersect the fiducial box
# (kaons going at large angles produce chi that miss the detector).
#
# Instead, fiducial selection is done entirely at the WEIGHT stage via
# fid_metric — events where V1_signal vertex is outside ICARUS get weight=0.
# This is physically equivalent: the upscatter cross section is negligible
# outside the LAr so essentially all signal comes from inside anyway.
#
# The chi upscatter free path is ~50 light-years (σ~10^-38 cm²) so most
# events get weight~0 from the cross section already. The effective signal
# comes from the rare chi that DO pass through the LAr and upscatter.
# ---------------------------------------------------------------------------
sv = distributions.SecondaryPhysicalVertexDistribution()

secondary_injection_distributions = {
    V1_PROD_TYPE:   [sv],   # V1 decays anywhere along chi path
    CHI_TYPE:       [sv],   # chi upscatters at physical interaction length
    CHI_PRIME_TYPE: [sv],   # chi' decays in-place (~1e-10 m)
    V1_SIG_TYPE:    [sv],   # V1_signal decays ~mm from upscatter vertex
}

# ===========================================================================
# SECTION 7 — STOPPING CONDITION
# Propagate: V1_prod, chi (only from V1_prod decay, index 0), chi', V1_signal
# Stop: e+, nu_e from kaon decay; chi recoil from upscatter; e+/e- from V1
# ===========================================================================

def stop(datum, i):
    sec    = int(datum.record.signature.secondary_types[i])
    parent = int(datum.record.signature.primary_type)
    if sec == PDGID_V1_PROD:   return False                          # V1_prod -> continue
    if sec == PDGID_CHI:       return parent != PDGID_V1_PROD or i != 0  # chi only from V1_prod[0]
    if sec == PDGID_CHI_PRIME: return False                          # chi' -> continue
    if sec == PDGID_V1_SIGNAL: return False                          # V1_signal -> continue
    return True                                                       # all else: stop

# ===========================================================================
# SECTION 8 — INJECTOR
# ===========================================================================

print("\nBuilding injector (%d events) ..." % events_to_inject)

# ---------------------------------------------------------------------------
# VertexWeightingMode.Fixed() — correct for dk2nu CSV input.
#
# From VertexWeightingMode.h:
#   "Fixed vertex: position externally determined (dk2nu, GENIE)."
# From DuttaKim_SBND_full_chain.py line 609:
#   primary_mode = injection.VertexWeightingMode.Fixed()
#
# Fixed() means the primary vertex came from an external source (dk2nu CSV)
# and SIREN uses EventsToInject()/GenerationProbability for weighting
# instead of InteractionProbability — which is correct because the kaon
# already decayed in the beamline simulation.
#
# Nan weights were caused by missing force-initialisation. The SBND chain
# (lines 657-659) runs one dummy iteration then resets the injector counter
# before production generation. This initialises internal weighter state.
# ---------------------------------------------------------------------------
_primary_mode = (siren.injection.VertexWeightingMode.Fixed()
                 if hasattr(siren.injection, "VertexWeightingMode") else None)

# Build secondary dists and phase spaces
_sec_dists = dict(secondary_injection_distributions)
_ps  = dict(secondary_phase_spaces)  if (_BIASING_AVAILABLE and secondary_phase_spaces)  else {}
_pps = dict(primary_phase_spaces)    if (_BIASING_AVAILABLE and primary_phase_spaces)     else {}

try:
    injector = siren.injection.Injector(
        number_of_events                  = events_to_inject,
        detector_model                    = detector_model,
        primary_type                      = KAON_TYPE,
        primary_interactions              = primary_processes[KAON_TYPE],
        primary_injection_distributions   = primary_injection_distributions,
        primary_weighting_mode            = _primary_mode,
        secondary_interactions            = secondary_processes,
        secondary_injection_distributions = _sec_dists,
        secondary_phase_spaces            = _ps,
        primary_phase_spaces              = _pps,
        stopping_condition                = stop,
    )
    print("  Injector built with keyword constructor")
except TypeError:
    # Older SIREN — use attribute-setting style
    injector = siren.injection.Injector()
    injector.number_of_events                  = events_to_inject
    injector.detector_model                    = detector_model
    injector.primary_type                      = KAON_TYPE
    injector.primary_interactions              = primary_processes[KAON_TYPE]
    injector.primary_injection_distributions   = primary_injection_distributions
    if _primary_mode is not None:
        injector.primary_weighting_mode        = _primary_mode
    injector.secondary_interactions            = secondary_processes
    injector.secondary_injection_distributions = _sec_dists
    if _ps:  injector.secondary_phase_spaces   = _ps
    if _pps: injector.primary_phase_spaces      = _pps
    injector.stopping_condition                = stop
    print("  Injector built with attribute-setting style")

print("  Primary weighting mode: Fixed (dk2nu CSV, per SBND chain pattern)")

# Force-initialise injector (SBND chain lines 657-659):
# Run one iteration to initialise internal weighter state, then reset counter.
print("  Force-initialising injector ...")
try:
    for _ev in injector:
        break
    injector._Injector__injector.ResetInjectedEvents(events_to_inject)
    print("  Injector force-initialised OK")
except Exception as _ei:
    print("  Init note:", _ei)

print("Generating %d events ..." % events_to_inject)

# ---------------------------------------------------------------------------
# Event generation — iterate injector directly (SBND chain pattern).
#
# Key insight from DuttaKim_SBND_full_chain.py line 694:
#   for event in injector:
#       if event.tree: events.append(event)
#
# This is the correct pattern for the full chain. GenerateEvents() calls
# injector.generate_event() once per event and appends regardless of whether
# the tree is populated — so events with empty trees (geometry misses) get
# included and pollute the output.
#
# Iterating the injector directly and filtering on event.tree means:
#   - Only events with actual interaction vertices are kept
#   - Geometry errors (Both points finite) produce empty trees and are skipped
#   - The injector handles its own retry logic internally
# ---------------------------------------------------------------------------
import time as _time

events    = []
gen_times = []
n_empty   = 0
n_errors  = 0
prev_time = _time.time()

try:
    for event in injector:
        t = _time.time()
        if event.tree:
            events.append(event)
            gen_times.append(t - prev_time)
            prev_time = t
            n = len(events)
            if n % 1000 == 0:
                print("  Generated %d / %d  (empty=%d geometry_errors=%d)"
                      % (n, events_to_inject, n_empty, n_errors))
        else:
            n_empty += 1
        if len(events) >= events_to_inject:
            break
except RuntimeError as e:
    err = str(e)
    if "finite" in err.lower() or "Both points" in err:
        n_errors += 1
        print("  Geometry error at event %d (total errors: %d)" % (len(events), n_errors))
        # Continue generating — restart the loop by re-calling generate_event directly
        while len(events) < events_to_inject:
            try:
                event = injector.generate_event()
                t = _time.time()
                if event.tree:
                    events.append(event)
                    gen_times.append(t - prev_time)
                    prev_time = t
                    n = len(events)
                    if n % 1000 == 0:
                        print("  Generated %d / %d  (empty=%d geometry_errors=%d)"
                              % (n, events_to_inject, n_empty, n_errors))
                else:
                    n_empty += 1
            except RuntimeError as e2:
                err2 = str(e2)
                if "finite" in err2.lower() or "Both points" in err2:
                    n_errors += 1
                elif "maximum number of injection" in err2.lower():
                    print("  Injector cap reached at %d events — stopping" % len(events))
                    break
                else:
                    raise
    else:
        raise

print("  Generated %d events  (empty=%d  geometry_errors=%d)"
      % (len(events), n_empty, n_errors))
print("Generated %d event trees." % len(events))

os.makedirs("output", exist_ok=True)

# ===========================================================================
# SECTION 9 — WEIGHTER
# Physical distributions: unbiased CSV + BSM branching ratio
# ===========================================================================

weighter = siren.injection.Weighter()
weighter.injectors                        = [injector]
weighter.detector_model                   = detector_model
weighter.primary_type                     = KAON_TYPE
weighter.primary_interactions             = primary_processes[KAON_TYPE]
weighter.secondary_interactions           = secondary_processes
weighter.primary_physical_distributions   = primary_physical_distributions
weighter.secondary_physical_distributions = {}

# ===========================================================================
# SECTION 10 — FIDUCIAL METRIC  (Gap 7 — ESF diagnostic)
# Only count events where V1_signal vertex is inside ICARUS fiducial.
# ===========================================================================

def make_fiducial_metric(fiducial, signal_pdgid=PDGID_V1_SIGNAL):
    from siren.math import Vector3D
    def metric(event, w):
        for datum in event.tree:
            r = datum.record
            if int(r.signature.primary_type) == signal_pdgid:
                vtx = Vector3D(*r.interaction_vertex[:3])
                if fiducial.IsInside(vtx):
                    return w
        return 0.0
    return metric

fid_metric = make_fiducial_metric(fiducial_volume)

# ===========================================================================
# SECTION 11 — OPTIONAL WEIGHT OPTIMIZATION  (Gap 6)
# Uncomment to run Kleiss-Pittau adaptive reweighting before production.
# Typical: 5 iterations × 200 events, then re-run GenerateEvents.
# ===========================================================================
# try:
#     from siren.optimize import optimize_chain_weights
#     print("\nOptimizing multi-channel weights ...")
#     optimize_chain_weights(
#         injector, weighter,
#         n_iterations = 5,
#         batch_size   = 200,
#         damping      = 0.5,
#         metric       = fid_metric,
#         verbose      = True,
#         min_weight   = 1e-4,
#     )
#     print("Regenerating events after optimization ...")
#     events, gen_times = GenerateEvents(injector)
#     print("Generated %d event trees." % len(events))
# except ImportError:
#     print("siren.optimize not available — skipping weight optimization")

# ===========================================================================
# SECTION 12 — SAVE + SUMMARY
# ===========================================================================

# ---------------------------------------------------------------------------
# Verify weights before saving — test on first 5 events
# ---------------------------------------------------------------------------
print("\nTesting weighter on first 5 events ...")
test_weights = []
for i, ev in enumerate(events[:5]):
    try:
        w = weighter(ev)
        test_weights.append(w)
        print("  Event %d: weight = %s" % (i, w))
    except Exception as e:
        print("  Event %d: ERROR = %s" % (i, e))
        test_weights.append(np.nan)

n_finite_test = sum(1 for w in test_weights if np.isfinite(w) and w > 0)
if n_finite_test == 0:
    print("WARNING: All test weights are nan/0 — Propagated mode may need")
    print("  the kaon vertex to be exactly on the world boundary.")
    print("  Check that z0 = -2501 cm and world box z-half = 2500 cm.")
else:
    print("  %d / %d test weights are finite and positive" %
          (n_finite_test, len(test_weights)))

# ---------------------------------------------------------------------------
# SaveEvents — with fallback if _util.py has the 'id' UnboundLocalError bug
# (siren/_util.py line 1116: datasets["num_interactions"].append(id+1)
#  where 'id' is unset for event trees with no interactions recorded)
# ---------------------------------------------------------------------------
try:
    SaveEvents(
        events, weighter, gen_times,
        fid_vol         = fiducial_volume,
        output_filename = output_stem,
    )
except UnboundLocalError as e:
    if "id" in str(e):
        print("WARNING: SaveEvents hit 'id' bug in _util.py — saving manually ...")
        # Manual save: write parquet directly
        import pandas as pd, pyarrow as pa, pyarrow.parquet as pq

        rows = []
        for ev_idx, (ev, gt) in enumerate(zip(events, gen_times)):
            try:
                w = weighter(ev)
            except Exception:
                w = 0.0
            rows.append({
                "event_id":   ev_idx,
                "weight":     float(w) if np.isfinite(w) else 0.0,
                "gen_time":   float(gt),
            })

        df_out = pd.DataFrame(rows)
        out_parquet = output_stem + ".parquet"
        df_out.to_parquet(out_parquet, index=False)
        print("  Saved %d events -> %s" % (len(rows), out_parquet))
    else:
        raise

try:
    xs.SaveInterpolationTables()
except Exception as _e:
    print("WARNING: xs.SaveInterpolationTables() failed (%s) — continuing" % _e)

primary_ups_keys  = {CHI_TYPE: [[xs.ups_case.nuclear_target]]}
secondary_dec_keys = {k: [[k]] for k in secondary_processes}
# SaveDarkNewsProcesses calls xs.save_to_table(), which this SIREN build's
# PyDarkNewsCrossSection wrapper does not expose. Interpolation tables and the
# events/parquet are already written, so a failure here is non-fatal.
try:
    SaveDarkNewsProcesses(
        table_dir,
        {CHI_TYPE: [xs]},   primary_ups_keys,
        secondary_processes, secondary_dec_keys,
    )
except Exception as _e:
    print("WARNING: SaveDarkNewsProcesses failed (%s) — continuing" % _e)

# Compute raw weights then apply fiducial metric
raw_weights = np.array([weighter(ev) for ev in events])
weights     = np.array([fid_metric(ev, w)
                        for ev, w in zip(events, raw_weights)])
finite_mask = np.isfinite(weights) & (weights > 0)
valid_w     = weights[finite_mask]

def effective_sample_fraction(w_all):
    """Kish effective sample size / N_total."""
    w = w_all[(np.isfinite(w_all)) & (w_all > 0)]
    if len(w) == 0:
        return 0.0
    return (w.sum()**2) / (len(w) * (w**2).sum()) * len(w) / len(w_all)

eff = effective_sample_fraction(weights) * 100.0

print()
print("=" * 60)
print("  RESULTS  —  ICARUS Vector Portal  K+ channel")
print("=" * 60)
print("  Chain          : K+(321) -> e+ nu_e V1 -> chi chi")
print("                   chi + Ar40 -> chi' + Ar40")
print("                   chi' -> chi + V1_sig -> e+e-  [VISIBLE]")
print("  m_chi          : %.0f MeV" % (M_CHI*1e3))
print("  m_chi'         : %.0f MeV" % (M_CHI_PRIME*1e3))
print("  m_V1           : %.0f MeV" % (M_V1*1e3))
print("  m_V2           : %.0f MeV" % (M_V2*1e3))
print("  BSM BR(K+)     : %.3e"     % br_bsm)
print("  Events generated         : %d"   % len(events))
print("  Finite positive weights  : %d / %d" % (finite_mask.sum(), len(weights)))
if len(valid_w) > 0:
    print("  Weight range             : %.3e  -  %.3e"
          % (valid_w.min(), valid_w.max()))
    print("  Weight mean              : %.3e" % valid_w.mean())
    print("  Weight stddev/mean       : %.2f" % (valid_w.std() / valid_w.mean()))
    print("  Effective sample frac.   : %.1f%%" % eff)
    print("  Total expected signal    : %.3e events" % valid_w.sum())
else:
    print("  WARNING: no finite positive weights!")
print("  Output -> %s.*" % output_stem)
print("=" * 60)
